drop table if exists tb_categoria CASCADE;

drop table if exists tb_livro CASCADE;

create table tb_categoria
(
    id   bigint generated by default as identity,
    nome varchar(255) not null,
    primary key (id)
);

create table tb_livro
(
    id           bigint generated by default as identity,
    codigo       bigint,
    nome         varchar(255) not null,
    paginas      bigint,
    preco        double,
    categoria_id bigint       not null,
    primary key (id)
);

alter table tb_livro
    add constraint FKi06a4xl65pv3wn0c4i3sxhbat
        foreign key (categoria_id)
            references tb_categoria;